S02 us78 specialization page
WildCodeSchool/expenssion-one pull request #10
Opened 2024-06-13 15:04 UTC by boubseb

look that's clean code!

2024-06-13 15:13 UTC, OCR-VH-DevWeb commented on src/app/app.routes.ts
> +    path: 'glossary/specialization',
Path in french please

2024-06-13 15:13 UTC, OCR-VH-DevWeb commented on src/app/pages/specialization-page/specialization-page.component.html
> +<section class="background_image">
background_image => background-image

2024-06-13 15:13 UTC, OCR-VH-DevWeb commented on src/app/pages/specialization-page/specialization-page.component.scss
> +  padding-left: $glossary_padding_left_desktop;
CamelCase for class name

2024-06-13 15:13 UTC, OCR-VH-DevWeb commented on src/app/styles/glossary.scss
> +.background_image {
same background-image better

2024-06-14 07:28 UTC, OCR-VH-DevWeb approved these changes

2024-06-14 07:40 UTC, Benja-san requested changes

2024-06-14 07:40 UTC, Benja-san commented on src/app/pages/specialization-page/specialization-page.component.html
> +    @for(specialization of specializations;track specialization){
ul li tags since you'll havce a list of specialization

2024-06-14 07:40 UTC, Benja-san commented on src/app/pages/specialization-page/specialization-page.component.html
> +                    <p class="text-description">
same here

2024-06-14 08:30 UTC, Benja-san approved these changes

2024-06-14 09:02 UTC, merged