S02 us81 location page
WildCodeSchool/expenssion-one pull request #11
Opened 2024-06-13 15:21 UTC by Kileana27

2024-06-13 15:31 UTC, OCR-VH-DevWeb commented on src/app/pages/location-page/location-page/location-page.component.scss
> +.location_content {
Choose between "-" or "_" for naming classes

2024-06-13 15:37 UTC, OCR-VH-DevWeb approved these changes

2024-06-14 07:29 UTC, Benja-san requested changes

2024-06-14 07:29 UTC, Benja-san commented on src/app/pages/location-page/location-page/location-page.component.html
you have a duplicated folder "location-page"

2024-06-14 07:29 UTC, Benja-san commented on src/app/pages/location-page/location-page/location-page.component.ts
> +    console.log(this.continents)
remove console logs (meant to debug only)

2024-06-14 07:42 UTC, Benja-san requested changes

2024-06-14 07:42 UTC, Benja-san commented on src/app/pages/location-page/location-page.component.html
> +            @for(continent of continents; track continent) {
use ul and li tags since you'll have a list of continents

2024-06-14 07:42 UTC, Benja-san commented on src/app/pages/location-page/location-page.component.html
> +                @for(region of continent.regions; track region) {
same here

2024-06-14 07:42 UTC, Benja-san commented on src/app/pages/location-page/location-page.component.html
> +                        @for(city of region.cities; track city) {
same here

2024-06-14 07:58 UTC, OCR-VH-DevWeb approved these changes

2024-06-14 08:17 UTC, OCR-VH-DevWeb approved these changes
Validate for last changes about location-page

2024-06-14 08:30 UTC, Benja-san approved these changes

2024-06-14 08:31 UTC, merged