S01 us25 pop up connexion Pull Request
WildCodeSchool/expenssion-one pull request #12
Opened 2024-06-13 16:17 UTC by cyrius83600

2024-06-14 07:24 UTC, OCR-VH-DevWeb commented on src/app/components/pop-up-mobile/pop-up-mobile.component.scss
> +  .connexionButton{
Warn => connexion is french! Change your name class pls

2024-06-14 07:25 UTC, OCR-VH-DevWeb approved these changes

2024-06-14 07:35 UTC, OCR-VH-DevWeb approved these changes

2024-06-14 08:00 UTC, Benja-san requested changes

2024-06-14 08:00 UTC, Benja-san commented on src/app/app.routes.ts
> +  // {
remove dead code

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/header/header.component.ts
> +    console.log('Clik OK');
remove console logs

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/header/header.component.ts
> +      console.log(`Dialog result: ${result}`);
remove console.log

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +            <div class="connect">
use Hx tag for titles

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +            <div class="formatText">
use label linked to correct input for navigation help and accessibility

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +            <div class="formatText">
same here

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
@OCR-VH-DevWeb @cyrius83600 please note you'll have to add validation to this form as an extra us for next sprint

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +                Mot de passe oublié ?
use a tag

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +            <button (click)="displayData()" class = "connectButton">Connexion</button>
submit type

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +            <button class = "registerButton">Inscription</button>
this is a link ? or a button leading to another popup?

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.ts
> +    console.log(this.login.login  + " " + this.login.password);
remove console log

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-mobile/pop-up-mobile.component.html
> +            <div class="connect">
title

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-mobile/pop-up-mobile.component.html
Duplicate content, use same component with media queries for CSS integration

2024-06-14 08:00 UTC, Benja-san commented on src/app/components/pop-up-mobile/pop-up-mobile.component.ts
duplicate content

2024-06-14 08:00 UTC, Benja-san commented on src/index.html
> +      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
are you using roboto font ?

2024-06-14 08:00 UTC, Benja-san commented on src/styles.scss
> +body { margin: 0; font-family: Roboto, "Helvetica Neue", sans-serif; }
don't see any roboto ff in figma layout

2024-06-14 10:01 UTC, cyrius83600 commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +            <div class="connect">
Impossible

2024-06-14 10:01 UTC, cyrius83600 commented on src/app/components/pop-up-mobile/pop-up-mobile.component.html
> +            <div class="connect">
Impossible

2024-06-14 12:18 UTC, OCR-VH-DevWeb approved these changes
Approved

2024-06-14 12:21 UTC, Benja-san requested changes

2024-06-14 12:21 UTC, Benja-san commented on src/app/components/header-mobile/header-mobile.component.ts
> +  openDialog() {
use openDialog as a service to avoid code duplication in both header components

2024-06-14 12:21 UTC, Benja-san commented on src/app/components/pop-up-connexion/pop-up-connexion.component.html
> +            SE CONNECTER
use Hx tag since this is a title

2024-06-20 07:29 UTC, AnassAmh approved these changes

2024-06-20 09:26 UTC, Benja-san approved these changes

2024-06-20 12:13 UTC, merged