S03 us76 secrets
WildCodeSchool/expenssion-one pull request #17
Opened 2024-06-18 13:43 UTC by cyrius83600

2024-06-20 08:37 UTC, AnassAmh submitted a review, later dismissed

2024-06-20 12:38 UTC, AnassAmh approved these changes

2024-06-20 12:50 UTC, AnassAmh approved these changes

2024-06-21 08:20 UTC, Benja-san requested changes

2024-06-21 08:20 UTC, Benja-san commented on src/app/components/header-mobile/header-mobile.component.html
> +                <a routerLink="glossaire/secrets"><li>Secrets</li></a>
put a inside li tags

2024-06-21 08:20 UTC, Benja-san commented on src/app/components/header/header.component.html
>                  <a routerLink="home"><li>Races</li></a>
same here

2024-06-21 08:20 UTC, Benja-san commented on src/app/pages/primordial-secrets-page/primordial-secrets-page.component.html
> +    <h1 class="title">Les secrets anecdotiques </h1>
only 1 H1 by page

2024-06-21 08:20 UTC, Benja-san commented on src/app/pages/primordial-secrets-page/primordial-secrets-page.component.html
> +    @for(secret of secrets;track secret) {
wrap this for into ul tag and use li to wrap your paragraphs

2024-06-21 08:54 UTC, cyrius83600 commented on src/app/pages/primordial-secrets-page/primordial-secrets-page.component.html
> +    <h1 class="title">Les secrets anecdotiques </h1>
Les 2 titres ont la meme importance d'ou les 2 H1

2024-06-21 10:20 UTC, Benja-san approved these changes

2024-06-21 10:24 UTC, merged