S03 us70 rules
WildCodeSchool/expenssion-one pull request #18
Opened 2024-06-20 09:52 UTC by Kileana27

2024-06-20 11:46 UTC, AnassAmh approved these changes
Parfait ! Rien à changer pour ma part.

2024-06-21 07:36 UTC, Benja-san requested changes

2024-06-21 07:36 UTC, Benja-san commented on src/app/components/header-mobile/header-mobile.component.html
> +            <a routerLink="accueil"><li>Création De Personnage</li></a>
a tags inside li and not the opposite

2024-06-21 07:36 UTC, Benja-san commented on src/app/components/header/header.component.html
> +                <a routerLink="regles"><li>Introduction</li></a>
a tag inside li and not the opposite

2024-06-21 07:36 UTC, Benja-san commented on src/app/components/header/header.component.html
> +                <a (click)="navigateToSection('reglesdujeu')"><li>Règles</li></a>
why don't you use a router link ?

2024-06-21 07:36 UTC, Benja-san commented on src/app/components/header-mobile/header-mobile.component.html
> +                <a (click)="navigateToSection('reglesdujeu')"><li>Règles</li></a>
why don't you use a router link ?

2024-06-21 07:36 UTC, Benja-san commented on src/app/pages/home-page/home-page.component.scss
> +    //width: 100vw;
remove dead code

2024-06-21 07:36 UTC, Benja-san commented on src/app/pages/rules-page/rules-page.component.ts
> +    this.route.fragment.subscribe((fragment: string|null) => {
need a talk about those lines

2024-06-21 08:04 UTC, Kileana27 commented on src/app/components/header-mobile/header-mobile.component.html
> +            <a routerLink="accueil"><li>Création De Personnage</li></a>
Not my us but corrected it

2024-06-21 08:04 UTC, Kileana27 commented on src/app/components/header/header.component.html
> +                <a routerLink="regles"><li>Introduction</li></a>
Not my us but corrected it

2024-06-21 08:05 UTC, Kileana27 commented on src/app/components/header/header.component.html
> +                <a (click)="navigateToSection('reglesdujeu')"><li>Règles</li></a>
Now using a router link thanks to you !

2024-06-21 08:05 UTC, Kileana27 commented on src/app/components/header-mobile/header-mobile.component.html
> +                <a (click)="navigateToSection('reglesdujeu')"><li>Règles</li></a>
Now using a router link thanks to you !

2024-06-21 08:05 UTC, Kileana27 commented on src/app/pages/home-page/home-page.component.scss
> +    //width: 100vw;
Removed

2024-06-21 08:22 UTC, Benja-san approved these changes

2024-06-21 08:45 UTC, merged