S03 us44 news page
WildCodeSchool/expenssion-one pull request #19
Opened 2024-06-20 12:05 UTC by AnassAmh

2024-06-20 14:48 UTC, Kileana27 commented on src/app/components/header-mobile/header-mobile.component.html
> +            <a routerLink="/News"><li routerLink="News">News</li></a>
routerLink ="news"

2024-06-20 14:48 UTC, Kileana27 commented on src/app/components/header/header.component.html
> +            <a routerLink="/News"><li routerLink="News">News</li></a>
routerLink ="news"

2024-06-20 14:48 UTC, Kileana27 commented on src/app/news-page/news-page.component.html
> +        <div class="news-item">
change div in art

2024-06-20 14:48 UTC, Kileana27 commented on src/app/news-page/news-page.component.html
> +        <div class="news-item">
change div in art

2024-06-20 14:48 UTC, Kileana27 commented on src/app/news-page/news-page.component.scss
> +    //background-color: rgba(15, 15, 15, 0.7);
dead code

2024-06-21 07:30 UTC, Benja-san requested changes

2024-06-21 07:30 UTC, Benja-san commented on src/app/carousel/carousel.component.html
> +<div class="carousel">
ul tag

2024-06-21 07:30 UTC, Benja-san commented on src/app/carousel/carousel.component.html
> +    <div class="carousel-slide" *ngFor="let slide of slides; let i = index" [class.active]="i === currentIndex"
li tag

2024-06-21 07:30 UTC, Benja-san commented on src/app/components/header-mobile/header-mobile.component.html
> +            <a routerLink="news"><li routerLink="news">News</li></a>
a tag should be inside the li tag and not the opposite

2024-06-21 07:30 UTC, Benja-san commented on src/app/news-page/news-page.component.html
> +    <article class="news-content">
section more than article

2024-06-21 07:30 UTC, Benja-san commented on src/app/news-page/news-page.component.html
your file need a unique H1

2024-06-21 08:37 UTC, Benja-san approved these changes

2024-06-21 08:59 UTC, Kileana27 approved these changes

2024-06-21 08:59 UTC, merged