S03 us44 news page
WildCodeSchool/expenssion-one pull request #31
Opened 2024-06-26 09:52 UTC by AnassAmh

Déplacement dans les bon dossiers

2024-06-26 10:30 UTC, Kileana27 approved these changes
All good !

2024-06-26 13:26 UTC, Benja-san requested changes

2024-06-26 13:26 UTC, Benja-san commented on src/app/app.routes.ts
> +    path: 'rules-page',
french content and english code

2024-06-27 13:17 UTC, Benja-san approved these changes

2024-06-27 13:19 UTC, merged