S04 us51 character creation secret
WildCodeSchool/expenssion-one pull request #36
Opened 2024-06-27 14:00 UTC by boubseb

2024-06-27 14:01 UTC, boubseb commented
short PR :D

2024-06-27 14:23 UTC, Kileana27 approved these changes

2024-06-27 15:00 UTC, Benja-san requested changes
Generate environment.development.ts, and add it to gitignore. 
Then let the global environment file at disposal with env variables in it (with placeholders for values)

add a tutorial in README.md to explain steps to do before launching server

doc here -> https://angular.fr/services/environment

2024-06-28 09:07 UTC, Benja-san approved these changes

2024-06-28 09:17 UTC, merged