S04 us146 stats
WildCodeSchool/expenssion-one pull request #38
Opened 2024-06-27 21:08 UTC by cyrius83600

2024-06-28 06:41 UTC, Kileana27 requested changes
Just little changes :)

2024-06-28 06:41 UTC, Kileana27 commented on src/app/pages/explain-state-page-desktop/explain-state-page-desktop.component.scss
> +    // }
Dead code

2024-06-28 06:41 UTC, Kileana27 commented on src/app/service/api-data.service.ts
> +  getStatistiques(): Observable<Statistiques[]> {
getStatistics in english

2024-06-28 08:07 UTC, Kileana27 approved these changes

2024-07-01 08:46 UTC, Benja-san requested changes

2024-07-01 08:46 UTC, Benja-san commented on src/app/pages/explain-state-page-desktop/explain-state-page-desktop.component.html
> +      <div class="flexRow">
ul and li when you have a list

2024-07-01 08:46 UTC, Benja-san commented on src/app/pages/explain-state-page-desktop/explain-state-page-desktop.component.html
> +        <div>
ul and li

2024-07-01 08:46 UTC, Benja-san commented on src/app/pages/explain-state-page-desktop/explain-state-page-desktop.component.html
> +    <p>On modifie le score en fonction de sa valeur</p>
use only one p wrapping all your lines and use "span" to wrapp the lines behind

2024-07-01 08:46 UTC, Benja-san commented on src/app/pages/stats-page/stats-page.component.html
> +        @for(stat of statistiques; track stat)
wrap this for in ul

2024-07-01 08:46 UTC, Benja-san commented on src/app/pages/stats-page/stats-page.component.html
> +<div class="background-image">
section

2024-07-01 08:46 UTC, Benja-san commented on src/app/pages/stats-page/stats-page.component.ts
> +            if(score >= 18) score = Math.round(score/2);
why ?

2024-07-02 13:20 UTC, Benja-san approved these changes

2024-07-03 07:30 UTC, merged