News character
WildCodeSchool/expenssion-one pull request #39
Opened 2024-06-28 06:36 UTC by AnassAmh

2024-06-28 06:48 UTC, Kileana27 approved these changes

2024-06-28 07:45 UTC, Benja-san requested changes

2024-06-28 07:45 UTC, Benja-san commented on src/app/app.routes.ts
> +    path: 'Character', component: NewsCharacterComponent
french content, english code

2024-06-28 07:45 UTC, Benja-san commented on src/app/pages/news-character/news-character.component.html
> +<div class="character-selection-container">
section tag

2024-06-28 07:45 UTC, Benja-san commented on src/app/pages/news-character/news-character.component.html
> +      <span>Ajouter un personnage</span>
h1 tag

2024-06-28 07:45 UTC, Benja-san commented on src/app/pages/news-character/news-character.component.html
> +    <div class="scroll-arrow" (click)="scroll('down')">▼</div>
button if click action

2024-06-28 07:45 UTC, Benja-san commented on src/app/pages/news-character/news-character.component.html
> +    <div class="scroll-arrow" (click)="scroll('up')">▲</div>
button if click action

2024-07-04 08:40 UTC, Benja-san approved these changes

2024-07-04 09:14 UTC, merged