S05 link backend user
WildCodeSchool/expenssion-one pull request #42
Opened 2024-07-07 15:40 UTC by boubseb

2024-07-08 11:09 UTC, OCR-VH-DevWeb approved these changes

2024-07-09 08:05 UTC, Benja-san requested changes

2024-07-09 08:05 UTC, Benja-san commented on src/app/service/user/user.service.ts
all those routes are configured on your backend ?

2024-07-09 08:05 UTC, Benja-san commented on src/app/pages/profil-parameter-page/profil-parameter-page.component.html
Add validation on forms / inputs, and related messages

2024-07-10 09:47 UTC, Benja-san approved these changes

2024-07-10 10:17 UTC, merged