S05 us172 worldmap
WildCodeSchool/expenssion-one pull request #51
Opened 2024-07-09 15:22 UTC by Kileana27

2024-07-09 15:32 UTC, OCR-VH-DevWeb approved these changes
Approved

2024-07-09 17:23 UTC, Benja-san requested changes

2024-07-09 17:23 UTC, Benja-san commented on src/app/app.routes.ts
> +    path: 'creationPersonnage/lieux',
use hyphen rather than camel cases for urls ?

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/norta-map/norta-map.component.ts
> +  selectedCity?: City= new City();
remove the ? or remove the empty city object

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/world-map-mobile/world-map-mobile.component.html
> +        @if (norta == true) {
===

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/world-map-mobile/world-map-mobile.component.html
> +        @if (nelm == true) {
===

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/world-map/world-map.component.html
> +        @if (norta == true) {
===

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/world-map/world-map.component.html
> +        @if (nelm == true) {
===

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/world-map-mobile/world-map-mobile.component.ts
> +}
all those methods can be refactored as one each (3 total) taking string as parameter

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/world-map/world-map.component.ts
> +    console.log("envoie")
remove console log

2024-07-09 17:23 UTC, Benja-san commented on src/app/components/world-map/world-map.component.ts
> +  }
same for those methods

2024-07-09 17:23 UTC, Benja-san commented on src/app/pages/location-selection-page/location-selection-page.component.html
> +            <h2>Lieu d'origine</h2>
every page should have at least one h1

2024-07-09 17:23 UTC, Benja-san commented on src/app/pages/location-selection-page/location-selection-page.component.ts
> +    console.log("reçu: " + this.isNortaDisplay);
remove clog

2024-07-10 10:21 UTC, Benja-san approved these changes

2024-07-10 10:29 UTC, merged